### ISSUE TITLE
SUSPENDED BUG

### ISSUE THREAD

**Issue by CarlOTA-Original** [jatintiwari0/FbCreator#1]
ALL THE FB ACCOUNT CREATED BY THE FILE WAS ALL SUSPENDED.

**Comment by jattin1** [comment]
Use proxy when your create account

**Comment by yosiefmalik** [comment]
the domain of mail.tm for creating mail is the reason of accounts checkpoint please can you replace code with new api for temp mail ..

**Comment by jattin1** [comment]
Ok
