### ISSUE TITLE
can you make it use sms-activate api instead of email

### ISSUE THREAD

**Issue by githubtrip** [jatintiwari0/FbCreator#5]
can you make it use sms-activate api instead of email

**Comment by jattin1** [comment]
Yes

**Comment by githubtrip** [comment]
What's your telegram. I can pay a fee for adding the phone number function.

**Comment by jattin1** [comment]
In this time feature cannot be add due to  Facebook have added high security captcha

**Comment by githubtrip** [comment]
cant we add captcha breaker service to solve captcha?

**Comment by jattin1** [comment]
It's hard to do
