### ISSUE TITLE
code no working

### ISSUE THREAD

**Issue by Danmingking** [jatintiwari0/FbCreator#8]
![pi](https://github.com/jatintiwari0/FbCreator/assets/174814926/efd647a5-2391-4d75-a127-d2d2bf7bdf43)

syntax error

**Comment by europecdc** [comment]
Nah, bro
To run the FBcreator.py file, you have two options:
**- Double-click on the FBcreator.py file with the left mouse button to run it directly.**
**- Open the console or terminal and navigate to the directory containing the FBcreator.py file, then enter the command python FBcreator.py to run the script.**
Additionally, make sure you have all the necessary modules installed, as listed in the repository. You'll need to ensure those dependencies are met before the script will run successfully ☺️

**Comment by Danmingking** [comment]
![trying](https://github.com/jatintiwari0/FbCreator/assets/174814926/bbe609c5-d00d-476d-a890-5c3f0ec35835)

okay i install all the modules and its working just like that.. then before i could do anything, it just auto close..

**Comment by Danmingking** [comment]
![trying](https://github.com/jatintiwari0/FbCreator/assets/174814926/402dd8e4-b50d-4cb0-abf8-25ee1cf0716b)

i try to install all the modules already, but after i run the FbCreator.py , it just shown like this for 1 second then auto close..

i install all the modules except the haslib
this the one coming out :
ERROR: Could not find a version that satisfies the requirement haslib (from versions: none)
ERROR: No matching distribution found for haslib

**Comment by europecdc** [comment]
Yes, but you should have not "haslib", but "hashlib"

**Comment by jattin1** [comment]
You'll need to ensure those dependencies are met before the script will run successfully 👍🏻

**Comment by Danmingking** [comment]
![724](https://github.com/jatintiwari0/FbCreator/assets/174814926/9c918a8a-bb00-45b9-888d-3226c37757d1)

i tried..
